### ISSUE TITLE
Qual a necessidade de se usar Kendoui?

### ISSUE THREAD

**Issue by enieber** [charlesviegas/az#1]
Olá, não tenho experiencia na utilização do Kendoui, mas tenho experiencia em desenvolvimento javascript, gostaria muito de saber qual a necessidade de utiliza lo como cliente já que o angular supriria bem a necessidade deste projeto, me corrija se eu estiver errado, mas o [Kendoui](http://www.telerik.com/kendo-ui#demo-charts) não é uma ferramenta pagar?

**Comment by charlesviegas** [comment]
Olá Enieber, de fato é uma ferramenta paga sim, porém ela oferece uma
dezena de widgets muito legais e avançados. Muito superior a qualquer
componente que vc encontra por aí em libs free. Alguns terceiros oferecem
algo parecido já com o angular, mas como disse muito inferior ao kendoui,
portanto se vc quiser fazer um sistema em nível profissional com muitos
requisitos não funcionais embutidos o kendoui é uma das melhores ofertas
neste mercado.

Em segunda-feira, 14 de dezembro de 2015, Enieber Cunha <
notifications@github.com> escreveu:

> Olá, não tenho experiencia na utilização do Kendoui, mas tenho experiencia
> em desenvolvimento javascript, gostaria muito de saber qual a necessidade
> de utiliza lo como cliente já que o angular supriria bem a necessidade
> deste projeto, me corrija se eu estiver errado, mas o Kendoui
> http://wwwtelerikcom/kendo-ui#demo-charts não é uma ferramenta pagar?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/charlesviegas/az/issues/1.

## 

*Charles *Viegas

**Comment by enieber** [comment]
entendo.. Talvez não seja a melhor ferramenta para se usar neste problema, mas já é uma.

**Comment by charlesviegas** [comment]
Eu usei esta prova pra um processo seletivo específico e acabei sugerindo
que o Alex utilizasse tb. Vc não precisa o kendoui. Aliás a priori o Alex
tb não vai usar, portanto faça do jeito que vc sabe. Ó importante é vc
conseguir demonstrar conhecimento e capacidade .

Em sexta-feira, 18 de dezembro de 2015, Enieber Cunha <
notifications@github.com> escreveu:

> entendo.. Talvez não seja a melhor ferramenta para se usar neste problema,
> mas já é uma.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/charlesviegas/az/issues/1#issuecomment-165905580.

## 

*Charles *Viegas
