### ISSUE TITLE
Unidade

### ISSUE THREAD

**Issue by enieber** [charlesviegas/az#2]
Qual o motivo para se criar uma tabela unidade?

**Comment by charlesviegas** [comment]
Só pra usar na combo. Mas acho que eu cortei a tela de cadastro do
leilão, então
não precisa não.

Em sexta-feira, 18 de dezembro de 2015, Enieber Cunha <
notifications@github.com> escreveu:

> Qual o motivo para se criar uma tabela unidade?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/charlesviegas/az/issues/2.

## 

*Charles *Viegas
